(global-display-line-numbers-mode 1)
(setq display-line-numbers-type 'relative)
(column-number-mode -1)
(menu-bar-mode -1)
(setq scroll-step 1)
(setq scroll-conservatively 10000)
(setq auto-window-vscroll nil)
(setq make-backup-files nil)
(setq auto-save-default nil)
